<%
const path = require('path');
const os = require('os');
const log_path = path.join(__dirname, '..', 'logs', `${process.env.NODE_ENV}.log`)
const broker_name = 'service-fabrik-broker';
const ip = '10.0.2.2';
const internal = {
  protocol: 'https',
  ip: ip,
  port: 9293
};
const external = {
  protocol: 'https',
  host: `${broker_name}.bosh-lite.com`,
  port: 9292
};
const redirect_uri = `${external.protocol}://${external.host}/manage/auth/cf/callback`;
%>---
########################################
# SERVICES CATALOG - BLUEPRINT SERVICE #
########################################
services:
- &blueprint_service
  id: '24731fb8-7b84-4f57-914f-c3d55d793dd4'
  name: 'blueprint'
  description: &description 'Blueprint service for internal development, testing, and documentation purposes of the Service Fabrik'
  bindable: true
  tags:
  - 'blueprint'
  - 'no-not-use'
  metadata:
    displayName: 'Blueprint'
    longDescription: *description
    providerDisplayName: 'SAP SE'
    documentationUrl: 'https://sap.com/'
    supportUrl: 'https://sap.com/'
  dashboard_client:
    id: 'service-fabrik-blueprint-client'
    secret: 'service-fabrik-blueprint-secret'
    redirect_uri: <%= redirect_uri %>
  plan_updateable: true
  plans:
  ###########################
  # CONTAINER SERVICE PLANS #
  ###########################
  - &blueprint_plan1
    id: '466c5078-df6e-427d-8fb2-c76af50c0f56'
    name: 'v1.0-dev'
    free: true
    manager:
      name: 'docker'
      settings:
        image: 'servicefabrikjenkins/blueprint'
        tag: 'latest'
        memory: '128m'
        persistent_volumes:
        - name: 'data'
          path: '/data'
          size: '100m'
    credentials:
      username:
        key: 'BLUEPRINT_USER_NAME'
      password:
        key: 'BLUEPRINT_USER_PASS'
      uri:
        prefix: 'http'
        port: 8080/tcp
    description: 'Blueprint 1.0 service running inside a Docker container (for non-productive usage)'
    metadata:
      costs:
      - amount:
          usd: 0.0
        unit: 'MONTHLY'
      bullets:
      - 'Container Deployment'
      - '128 MB Memory'
      - '100 MB Disk'
  - &blueprint_plan2
    id: '6a252f89-c974-4ef9-a4de-c49f300de39a'
    name: 'v1.0-dev-large'
    free: true
    manager:
      name: 'docker'
      settings:
        image: 'servicefabrikjenkins/blueprint'
        tag: 'latest'
        memory: '256m'
        persistent_volumes:
        - name: 'data'
          path: '/data'
          size: '200m'
    credentials:
      username:
        key: 'BLUEPRINT_USER_NAME'
      password:
        key: 'BLUEPRINT_USER_PASS'
      uri:
        prefix: 'http'
        port: 8080/tcp
    description: 'Blueprint 1.0 service running inside a large Docker container (for non-productive usage)'
    metadata:
      costs:
      - amount:
          usd: 0.0
        unit: 'MONTHLY'
      bullets:
      - 'Container Deployment'
      - '256 MB Memory'
      - '200 MB Disk'